# Generated by Django 3.0.1 on 2020-01-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'unique_together': {('title', 'img_path')},
            },
        ),
    ]
