# Generated by Django 3.0.3 on 2020-02-29 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerapplication',
            name='message',
        ),
        migrations.AddField(
            model_name='ownerapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownerapplication',
            name='company',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='ownerapplication',
            name='name',
            field=models.CharField(max_length=56),
        ),
    ]
