# Generated by Django 3.0.1 on 2020-01-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
