# Generated by Django 3.0.1 on 2020-01-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phone_number',
        ),
    ]
