# Generated by Django 3.0.3 on 2020-02-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_ownerapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerapplication',
            name='company',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='ownerapplication',
            name='name',
            field=models.CharField(max_length=56),
        ),
    ]
