# Generated by Django 3.0.3 on 2020-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200304_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
