# Generated by Django 3.0.1 on 2020-01-17 01:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_contactus_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PH'),
        ),
    ]
