# Generated by Django 3.0.1 on 2020-01-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_barangay_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('message', models.TextField(max_length=256)),
            ],
        ),
    ]
