# Generated by Django 3.0.1 on 2020-01-17 01:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True)),
                ('company', models.CharField(max_length=56, unique=True)),
                ('email', models.EmailField(max_length=40)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('message', models.TextField(max_length=150)),
            ],
        ),
    ]
