# Generated by Django 3.0.1 on 2020-01-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_site_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='name',
            new_name='title',
        ),
    ]
