# Generated by Django 3.0.1 on 2020-01-10 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='\\media\x0ciles')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='\\media\\images')),
            ],
            options={
                'unique_together': {('title', 'img_path')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True)),
                ('street', models.CharField(max_length=56)),
                ('brgy', models.CharField(max_length=56)),
                ('city', models.CharField(max_length=56)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'unique_together': {('name', 'street', 'brgy', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField(default=1)),
                ('number', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('room_type', models.IntegerField(choices=[(0, 'Fixed Rate'), (1, 'Submetered')], default=0)),
                ('image_2d', models.ManyToManyField(blank=True, related_name='images_2d', to='roomy_core.ImageFile')),
                ('image_3d', models.ManyToManyField(blank=True, related_name='images_3d', to='roomy_core.ImageFile')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Property')),
            ],
            options={
                'unique_together': {('property_id', 'floor', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Room')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Tenant'), (2, 'Owner/Manager')], default=0)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('cell_number', models.PositiveIntegerField(blank=True, null=True)),
                ('provincial_address', models.CharField(blank=True, max_length=128, null=True)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Transaction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=56)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('inside', models.BooleanField(default=True)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=56)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'unique_together': {('description', 'amount')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=56)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('add_ons', models.ManyToManyField(blank=True, to='roomy_core.Fee')),
                ('document1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document1', to='roomy_core.Document')),
                ('document2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document2', to='roomy_core.Document')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('billing_fee', models.ManyToManyField(blank=True, to='roomy_core.Fee')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Transaction')),
            ],
        ),
    ]
