# Generated by Django 3.0.1 on 2020-01-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Property'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.ImageField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Transaction'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Tenant'), (2, 'Manager'), (3, 'Owner')], default=0),
        ),
    ]
