# Generated by Django 3.0.1 on 2020-01-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
