# Generated by Django 3.0.1 on 2020-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0002_auto_20200125_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
