# Generated by Django 3.0.3 on 2020-02-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0002_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Occupied'), (2, 'Unavailable')], default=0),
        ),
    ]
