# Generated by Django 3.0.1 on 2020-01-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0002_auto_20200120_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='document1_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document1', to='roomy_core.Document'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='document2_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document2', to='roomy_core.Document'),
        ),
    ]
