# Generated by Django 3.0.1 on 2020-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0002_auto_20200113_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ManyToManyField(blank=True, related_name='property_image', to='roomy_core.ImageFile'),
        ),
    ]
