# Generated by Django 3.0.1 on 2020-02-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0002_auto_20200128_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.BooleanField(default=True),
        ),
    ]
