# Generated by Django 3.0.1 on 2020-01-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0002_room_name'),
        ('roomy_core', '0003_auto_20200120_0642'),
    ]

    operations = [
    ]
