# Generated by Django 3.0.1 on 2020-01-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0003_auto_20200113_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.IntegerField(choices=[(0, 'Misc Fees'), (1, 'Add-ons')], default=0),
        ),
    ]
