# Generated by Django 3.0.1 on 2020-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0003_auto_20200304_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownernotification',
            name='time_stamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
