# Generated by Django 3.0.1 on 2020-01-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0003_auto_20200106_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='\\media\\images')),
            ],
            options={
                'unique_together': {('title', 'img_path')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='image_2d',
            field=models.ManyToManyField(blank=True, related_name='images_2d', to='roomy_core.ImageFile'),
        ),
        migrations.AddField(
            model_name='room',
            name='image_3d',
            field=models.ManyToManyField(blank=True, related_name='images_3d', to='roomy_core.ImageFile'),
        ),
    ]
