# Generated by Django 3.0.3 on 2020-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0003_auto_20200222_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(0, 'Vacant'), (1, 'Shared'), (2, 'Unavailable')], default=0),
        ),
    ]
