# Generated by Django 3.0.1 on 2020-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0003_auto_20200220_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Processed'), (2, 'Denied')], default=0),
        ),
    ]
