# Generated by Django 3.0.1 on 2020-01-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0004_merge_20200121_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=56, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('property_id', 'floor', 'number')},
        ),
    ]
