# Generated by Django 3.0.1 on 2020-01-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0004_auto_20200125_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.TenantAccount'),
        ),
    ]
