# Generated by Django 3.0.1 on 2020-01-22 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0005_auto_20200122_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=56, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Property')),
            ],
            options={
                'unique_together': {('property_id', 'name')},
            },
        ),
    ]
