# Generated by Django 3.0.1 on 2020-01-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0005_auto_20200115_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
