# Generated by Django 3.0.1 on 2020-02-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0005_ownernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time_stamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='owneraccount',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantaccount',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('description', 'amount')},
        ),
    ]
