# Generated by Django 3.0.1 on 2020-01-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0005_auto_20200122_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Transaction'),
        ),
    ]
