# Generated by Django 3.0.1 on 2020-01-22 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0006_roomcatalogue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomCatalogue',
            new_name='RoomCatalog',
        ),
        migrations.AddField(
            model_name='room',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.RoomCatalog'),
            preserve_default=False,
        ),
    ]
