# Generated by Django 3.0.1 on 2020-01-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0006_message_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
    ]
