# Generated by Django 3.0.1 on 2020-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0007_auto_20200115_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='add_ons',
            field=models.ManyToManyField(blank=True, to='roomy_core.Fee'),
        ),
    ]
