# Generated by Django 3.0.1 on 2020-01-21 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0007_remove_message_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='message',
            name='tenant_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.TenantAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 22, 3, 7, 30, 922782)),
            preserve_default=False,
        ),
    ]
