# Generated by Django 3.0.1 on 2020-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0007_booking_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='add_ons',
            field=models.ManyToManyField(blank=True, null=True, to='roomy_core.Fee'),
        ),
    ]
