# Generated by Django 3.0.1 on 2020-02-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0008_auto_20200225_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='add_ons',
            field=models.ManyToManyField(blank=True, to='roomy_core.Fee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Transaction'),
        ),
    ]
