# Generated by Django 3.0.1 on 2020-01-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0008_auto_20200122_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.RoomCatalog'),
        ),
    ]
