# Generated by Django 3.0.1 on 2020-01-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0009_auto_20200122_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcatalog',
            name='img_2d',
            field=models.ManyToManyField(blank=True, related_name='img_2d', to='roomy_core.ImageFile'),
        ),
        migrations.AddField(
            model_name='roomcatalog',
            name='img_3d',
            field=models.ManyToManyField(blank=True, related_name='img_3d', to='roomy_core.ImageFile'),
        ),
    ]
