# Generated by Django 3.0.1 on 2020-01-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0009_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
