# Generated by Django 3.0.1 on 2020-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0009_auto_20200225_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='billing_date',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
