# Generated by Django 3.0.1 on 2020-01-22 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0010_auto_20200122_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomy_core.RoomCatalog'),
        ),
    ]
