# Generated by Django 3.0.1 on 2020-01-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomy_core', '0010_auto_20200116_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('cell_number', models.PositiveIntegerField(blank=True, null=True)),
                ('provincial_address', models.CharField(blank=True, max_length=128, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('cell_number', models.PositiveIntegerField(blank=True, null=True)),
                ('provincial_address', models.CharField(blank=True, max_length=128, null=True)),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Transaction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AddField(
            model_name='property',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.OwnerAccount'),
        ),
    ]
