# Generated by Django 3.0.1 on 2020-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0011_auto_20200122_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcatalog',
            name='room_type',
            field=models.IntegerField(choices=[(0, 'Fixed Rate'), (1, 'Submetered')], default=0),
        ),
    ]
