# Generated by Django 3.0.1 on 2020-01-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0011_auto_20200116_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Property'),
        ),
    ]
