# Generated by Django 3.0.1 on 2020-01-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0013_message_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.IntegerField(choices=[(0, 'Condomenium'), (1, 'Dormitory'), (2, 'Apartment')], default=0),
        ),
    ]
