# Generated by Django 3.0.1 on 2020-01-17 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0014_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rating_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set(),
        ),
    ]
