# Generated by Django 3.0.1 on 2020-01-17 11:14

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0015_auto_20200117_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='brgy',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='street',
        ),
        migrations.AddField(
            model_name='property',
            name='property_address',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
    ]
