# Generated by Django 3.0.1 on 2020-01-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0016_auto_20200117_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
