# Generated by Django 3.0.1 on 2020-01-19 05:39

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0017_auto_20200119_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_address',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
    ]
