# Generated by Django 3.0.1 on 2020-01-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0004_auto_20200107_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
