# Generated by Django 3.0.1 on 2020-01-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomy_core', '0005_auto_20200109_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='property_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roomy_core.Property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='add_ons',
            field=models.ManyToManyField(blank=True, to='roomy_core.Fee'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Tenant'), (2, 'Owner/Manager')], default=0),
        ),
    ]
